### ISSUE TITLE
windows下运行报错

### ISSUE THREAD

**Issue by EmpRamses** [WiseDoge/ProxyPool#2]
Traceback (most recent call last):
  File "C:\Users\empra\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 2299, i
n resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'run' has no attribute 'cli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\empra\AppData\Local\Programs\Python\Python36\Scripts\proxypool_run-script.py", line 11, in <module>
    load_entry_point('proxypool==1.0.0', 'console_scripts', 'proxypool_run')()
  File "C:\Users\empra\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 565, in
 load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\empra\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 2631, i
n load_entry_point
    return ep.load()
  File "C:\Users\empra\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 2291, i
n load
    return self.resolve()
  File "C:\Users\empra\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 2301, i
n resolve
    raise ImportError(str(exc))
ImportError: module 'run' has no attribute 'cli'

**Comment by liuslnlp** [comment]
已经修改
