### ISSUE TITLE
开始运行就报错

### ISSUE THREAD

**Issue by littleant1111** [WiseDoge/ProxyPool#5]
报错信息：
[root@host_79 ProxyPool-master]# python run.py 
Expire Check Process is working..
PoolAdder is working

Process ProxyCountCheckProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/spider/proxyPool2/ProxyPool-master/proxypool/schedule/schedule.py", line 60, in run
    adder.add_to_pool()
  File "/home/spider/proxyPool2/ProxyPool-master/proxypool/schedule/adder.py", line 36, in add_to_pool
    raw_proxies.extend(future.result())
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/spider/proxyPool2/ProxyPool-master/proxypool/spiders.py", line 101, in gets
    {'class': 'table table-bordered table-striped'}) \
AttributeError: 'NoneType' object has no attribute 'find'

配置文件：
# Redis Host
HOST = 'localhost'
# Redis PORT
PORT = 6379

# Redis 中存放代理池的 Set 名
POOL_NAME = 'proxies'

# Pool 的低阈值和高阈值
POOL_LOWER_THRESHOLD = 10
POOL_UPPER_THRESHOLD = 40

# 两个调度进程的周期
VALID_CHECK_CYCLE = 600
POOL_LEN_CHECK_CYCLE = 20

# headers
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 \
    (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36',
    'Accept-Encoding': 'gzip, deflate, sdch',
    'Accept-Language': 'zh-CN,zh;q=0.8'
}

望提示，谢谢！

**Comment by liuslnlp** [comment]
如果是一上来就报这个错，说明网站的前端代码换了，需要对应着改一下爬虫的代码。如果是运行了一会报的这个错，说明是爬虫的速度太快了，你需要增大一下抓取间隔。
---------------------------------------------------
Liu ShiLei
Shandong Agricultural University
Github: https://github.com/WiseDoge
---------------------------------------------------
________________________________
发件人: guanghua.fan <notifications@github.com>
发送时间: 2017年9月12日 8:57:20
收件人: WiseDoge/ProxyPool
抄送: Subscribed
主题: [WiseDoge/ProxyPool] 我运行就报错？ (#5)


报错信息：
[root@host_79 ProxyPool-master]# python run.py
Expire Check Process is working..
PoolAdder is working

Process ProxyCountCheckProcess-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
self.run()
File "/home/spider/proxyPool2/ProxyPool-master/proxypool/schedule/schedule.py", line 60, in run
adder.add_to_pool()
File "/home/spider/proxyPool2/ProxyPool-master/proxypool/schedule/adder.py", line 36, in add_to_pool
raw_proxies.extend(future.result())
File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 398, in result
return self.__get_result()
File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
raise self._exception
File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/spider/proxyPool2/ProxyPool-master/proxypool/spiders.py", line 101, in gets
{'class': 'table table-bordered table-striped'})
AttributeError: 'NoneType' object has no attribute 'find'

配置文件：

Redis Host

HOST = 'localhost'

Redis PORT

PORT = 6379

Redis 中存放代理池的 Set 名

POOL_NAME = 'proxies'

Pool 的低阈值和高阈值

POOL_LOWER_THRESHOLD = 10
POOL_UPPER_THRESHOLD = 40

两个调度进程的周期

VALID_CHECK_CYCLE = 600
POOL_LEN_CHECK_CYCLE = 20

headers

HEADERS = {
'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36',
'Accept-Encoding': 'gzip, deflate, sdch',
'Accept-Language': 'zh-CN,zh;q=0.8'
}

望提示，谢谢！

―
